TARGET_ARCH := arm64
TARGET_CPU_VARIANT := cortex-a73
TARGET_CPU_ABI := arm64-v8a
TARGET_BOARD_PLATFORM := mt6771

BOARD_BOOTIMG_HEADER_VERSION := 2
BOARD_KERNEL_IMAGE_NAME := Image.gz-dtb
TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64
